# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
#########################
# Travis CI configuration
#########################
---

# Run tests against master branch only
if: branch IN (master)

language: generic

script:
  - asdf plugin-test aws-vault ${TRAVIS_BUILD_DIR} "aws-vault --version"

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

os:
  - linux
  - osx

env:
  global:
    secure: >-
      sSAcd7EXzvwt/bBPFnloktmwSutVD2Q01HTFye4Gzrvs43/dbAgjsyQhJ3rvE4eeDc3IllYbKB
      rVLDYMYL7S2lRGx5NoSCCAywIz8D3OtySxR1hX/d91q8AQxWGt/1dYfRMfj/jeNRL1pDtVtCd0
      n1AnDwCSPuagGXZj2O307z5KznRHKgFcR9VpInNM6aPnPDfCmJAPdfDNtP6BHLXwNRMSkAIdlC
      gIvyOWus2kz3eluf/xX5SsGatcFEadT/3L+jehlrhFVTN5IzciS6KZxTRmccOTSLnvRrxsWbky
      m+zHzXxHl9/heSLm13PDOAXQr+YSy3OehTO4FTs5H6eRTEk94VfRipMB4aGADco6goQt11axNY
      x0wcsvj40P41ws61TM58nmpkinoYDxb6mVDxMiIfmrcJVDLm/IVkmtGv+N9+5+Kkdr5Qy6TxBd
      ZMHWLhNiRqlhAN5QdlO5OyS1yjP5cCbxXNz6YsONFswTUxwt9RrNXKPxWQQIYlY1IDL3lO1WWK
      cqD5k2XhsicazKnoeUNabH1urCX6ha+/sWWWGUxRSJUnWFZTZNioscoPCKzPtVyU78EFXGhxmG
      Iaf3tD1sNdxJE+e4wIirLseTFzw87aaCVOoA0B9RwkCR7lQl79/tda4SnRMjo1kZi3ndbybgZw
      R2EV5T4s2NKGBKAyg=
