# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
#########################
# Travis CI configuration
#########################
---

# Run tests against master branch only
if: branch IN (master)

language: generic

script: 
  - asdf plugin-test aws-vault https://github.com/markosamuli/asdf-aws-vault.git "aws-vault --version"

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

os:
  - linux
  - osx