language: generic

script: 
  - asdf plugin-test aws-vault https://github.com/markosamuli/asdf-aws-vault.git "aws-vault --version"

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

os:
  - linux
  - osx